project_name: "AAI-590-G3-ASL"
subset: "WLASL100"
fps: 25

paths:
  repo_root: "."
  raw_dir: "data/raw"
  videos_dir: "data/videos"
  metadata_dir: "data/metadata"
  checkpoints_dir: "checkpoints"
  logs_dir: "runs"

wlasl:
  json_file: "data/metadata/WLASL_flat.json"   # place the JSON here
  split_seed: 42
  top_k: 100

train:
  batch_size: 8
  num_workers: 6
  epochs: 30
  lr: 1e-3
  weight_decay: 1e-4
  amp: true
  resume_checkpoint: null
  save_best_metric: "val_top1"

model:
  name: "r3d_18"
  pretrained: true
  num_classes: 100
  clip_len: 16
  frame_stride: 2
  input_size: [112, 112]
